#!/bin/sh
#
# Startup network interfaces....
#

case "$1" in
  start)
	echo "Starting network..."
	if [ `grep -c static /pulsarroot/configs/network/interfaces` != "0" ]; then
		/sbin/ifup -a
		echo "ok" > /var/run/network.pid
	else
        	/sbin/udhcpc -p /var/run/network.pid
	fi
        ;;
  stop)
        echo -n "Stopping network..."
	if [ `grep -c /pulsarroot/configs/network/interfaces` != "0" ]; then
		/sbin/ifdown -a
		rm /var/run/network.pid
	else
		kill -9 `cat /var/run/udhcpc.pid`
	fi
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
