#! /bin/sh
#
# System-V init script for the openntp daemon
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="network time protocol daemon"
NAME=ntpd
DAEMON=/usr/sbin/$NAME
NTPDATE_BIN=/usr/bin/ntpdate
NTPDATE_OPTS="-p /var/run/ntpd.pid"

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /pulsarroot/configs/default/$NAME ]
then
	. /pulsarroot/configs/default/$NAME
fi

case "$1" in
  start)
	if test x$NTPDATE = xyes ; then
		echo -n "Getting initial time via ntp"
		$NTPDATE_BIN $NTPDATE_OPTS $NTPSERVERS > /dev/null 2>&1
		echo "."
	fi
	if test x$NTPD = xyes ; then
		echo -n "Starting $DESC: $NAME"
		$DAEMON
		echo "."
	fi
	;;
  stop) echo -n "Stopping $DESC: $NAME"
	kill -9 `cat /var/run/ntpd.pid`
	echo "."
	;;
  reload|force-reload) echo -n "Reloading $DESC configuration..."
	kill -HUP `cat /var/run/udhcpc.pid`
	echo "done."
  ;;
  restart) echo "Restarting $DESC: $NAME"
	$0 stop
	sleep 1
	$0 start
	;;
  *) echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
