#! /bin/ksh

PKGADD=/usr/sbin/pkgadd
PKGLIST=packages
PKGADMIN=admin
PKGDIR=/export/ws/isoimage/s10u1/Solaris_10/Product
PKGLOG=packages.log
ROOTDIR=/a/miniroot

for pkg in `cat $PKGLIST`; do
	if [ ! -d "$PKGDIR/$pkg" ]; then
		echo "	$pkg: not found in $PKGDIR"
	else
		echo "	$pkg added to $ROOTDIR"
		$PKGADD -a $PKGADMIN -d $PKGDIR -R $ROOTDIR $pkg > PKGLOG 2>&1
	fi
done
