#!/bin/sh

ROOTDIR=/a/miniroot

cd $ROOTDIR

if [ "$ROOTDIR" = / ] ; then
        echo You probably do not want to run this in /.
        echo Please cd into the top level of an unpacked miniroot to run this.
        exit
fi

# Strip amd64 binaries
echo "strip amd64 binaries"
find . -name amd64 | xargs rm -r 2> /dev/null

# remove packaging, xpg4, sfw
echo "strip packaging, xpg4, and freeware"
rm -r var/sadm/* usr/xpg4 usr/sfw

# fix etc/vfstab
echo "fix /etc/vfstab and /etc/nodename"
echo "/devices/ramdisk:a - / ufs - no nologging" >> etc/vfstab
echo "embedded" > $ROOTDIR/etc/nodename

#
# Set the environment variables for svccfg.
#
echo "customize SMF services"
SVCCFG_DTD=$ROOTDIR/usr/share/lib/xml/dtd/service_bundle.dtd.1
SVCCFG_REPOSITORY=$ROOTDIR/etc/svc/repository.db
SVCCFG=/usr/sbin/svccfg

export SVCCFG_DTD SVCCFG_REPOSITORY SVCCFG

$SVCCFG import $ROOTDIR/var/svc/manifest/milestone/sysconfig.xml

# turnoff boot-archive, rpc bind, ipfilter, manifest-import
$SVCCFG -s system/boot-archive setprop start/exec=:true
$SVCCFG -s system/manifest-import setprop start/exec=:true
$SVCCFG -s network/rpc/bind delpg sysidtool
$SVCCFG -s network/rpc/bind:default setprop general/enabled=false
$SVCCFG -s network/pfil:default setprop general/enabled=false
$SVCCFG -s system/metainit:default setprop general/enabled=false
