#!/sbin/sh
#
#############
# JTC: Modified fs-minimal service which:
#    (1) Mounts /var as a tmpfs
#    (2) After mounting root, removes a previously allocated /FREESPACE file
#        to get some amount of free space in the root directory.
#############
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
# The copyright notice above does not evidence any
# actual or intended publication of such source code.
#
# ident	"@(#)fs-minimal	1.31	04/12/22 SMI"

. /lib/svc/share/smf_include.sh
. /lib/svc/share/fs_include.sh

# Mount other file systems to be available in single user mode.
# Currently, these are /var, /var/adm, /var/run and /tmp.  A change
# here will require a modification to the following programs (and
# documentation): /sbin/mountall, /sbin/umountall, and
# /lib/svc/bin/svc.startd.

for fs in /var /var/adm /tmp; do
	readvfstab $fs < $vfstab
	if [ -n "$mountp" ]; then
		mounted $mountp $mntopts $fstype < /etc/mnttab && continue
		checkfs $fsckdev $fstype $mountp || exit $SMF_EXIT_ERR_FATAL
		mountfs -O $mountp $fstype $mntopts - ||
		    exit $SMF_EXIT_ERR_FATAL
	fi
done

#
# Don't mount /var/run because we mount /var as tmpfs
#
#mounted /var/run - tmpfs < /etc/mnttab && exit $SMF_EXIT_OK
#mountfs -O /var/run tmpfs - swap || exit $SMF_EXIT_ERR_FATAL

#
# Reconstitute /var filesystem
#
cd /
tar xf /var.tar
/bin/rm -rf /var.tar

#
# Remove /FREESPACE file to reclaim some free space on /
#
/bin/rm -rf /FREESPACE

exit $SMF_EXIT_OK
